### ISSUE TITLE
support from vscode 1.51.1 instead of only 1.52

### ISSUE THREAD

**Issue by gsmachado** [ngdenterprise/neo3-visual-tracker#30]
Instead of only supporting 1.52 family, could you guys check if the 1.51 is also good to go?

Because the highest version of vscode that neo-playground supports until now is the 1.51.1, and it's quite some work for us to change it.

I assume you guys are not using any special functionality of the 1.52, and could also support from 1.51.1 onwards.

https://github.com/ngdenterprise/neo3-visual-tracker/blob/master/package.json#L14

**Comment by djnicholson** [comment]
That's fine, I can drop back to 1.51.

The only reason I moved to 1.52 was because I did an npm update, not because I needed anything from that version.

**Comment by gsmachado** [comment]
@djnicholson awesome.

Could you somehow override the previous release? Or make another one?

Then I could already integrate into what we're doing here.

BTW: great work!

**Comment by djnicholson** [comment]
Thanks!

Updated release to follow shortly...

**Comment by djnicholson** [comment]
New release: https://github.com/ngdenterprise/neo3-visual-tracker/releases/tag/v0.5.425-preview
