### ISSUE TITLE
discussion: language agnostic?

### ISSUE THREAD

**Issue by gsmachado** [ngdenterprise/neo3-visual-tracker#33]
Hey @devhawk @JohndeVadoss @djnicholson 

I just want to raise a discussion here. I observed that the `neo3-visual-tracker` is going in a direction that it's not totally language agnostic.

I will give an example: on the left bar, in the "quick start", there's a button which is to "Create a new contract". This button is specifically tailored to C#, and, therefore, persuades the user to do that. This is not a bad thing, though! In fact, this is great! It motivates developers to start doing something. However, if users already have a python, Java, golang, javascript development environment, this is somehow confusing. I showed this to a friend, and he mentioned the same.

This is even more confusing if we use the neo3-visual-tracker in the Neo Playground, where templates/examples can be of any language.

I give you three suggestions. Either one would make things way better:
1) Don't put so much emphasis on the "Create a new contract" in C# feature. Hide that function in a sub-menu, somewhere. This function, after all, it's nice to have!
2) Change the button name to "Create a new C# contract" and remove any text on top of the button. Also, add that button to the end of the Quick Start (less emphasis).
3) Provide a vscode extension option to disable that feature, completely, as a feature toggle (hiding this function).
4) Add support to create a new smart contract as a template from C#, go, javascript, Java, Kotlin, and python. (challenging and time consuming, but ideal).

Well... after all, I understand the natural focus to C# that Neo has. However, if the Neo ecosystem "advertises" that people can develop in different languages **and** given the fact that neo3-visual-tracker is an "enabler" for this ecosystem, I think it's nice to move to a more language-agnostic tool. 👍 

What do you think about this?

**Comment by gsmachado** [comment]
@devhawk to be honest, I would prefer having option 3) implemented first. That would be the best, IMHO.

**Comment by devhawk** [comment]
I think option 4 is the right long term approach. I looked a little into extensible VSCode extensions for token designer. It appears that VSCode extensions can provide their own contribution points. For example, the [official Markdown extension supports](https://code.visualstudio.com/api/extension-guides/markdown-extension) custom styling, custom scripts and custom markdown processing. I could see a similar approach for devtracker to support custom new contract templates - not just for multi language support, but also for multiple templates in a given langage (create new basic C# contract, create new fungible token C# contract, create new non-fungible C# contract, etc).

In the short term, options 2 + 3 seem like the right approach

**Comment by djnicholson** [comment]
A shorter timeframe option (4) would be to just allow contribution of new templates to the devtracker repo via pull requests.  There will probably only ever be a handful of implementations so maintenance via pull request won't be too much of a burden.  These templates are just text files in the repo with a pretty simple string substitution to get the contract name.

**Comment by djnicholson** [comment]
@gsmachado could you show me an example Hello-World contract in any language of your choice that is not C#?  Ideally with build config for whatever build system is most typically used for that language, and a VS Code tasks.json that can trigger the build within VS Code.

**Comment by gsmachado** [comment]
> @gsmachado could you show me an example Hello-World contract in any language of your choice that is not C#? Ideally with build config for whatever build system is most typically used for that language, and a VS Code tasks.json that can trigger the build within VS Code.

I will provide you an example in Java. 😄 

But, let me clarify something:

A Java/Kotlin project is not only composed of a single file. Besides the `build.gradle` file and the `Contract.java` file (which is the source code of a Smart Contract, there are other files that are required. Not many, but a few more

So...

- Should I provide you a .zip with a minimum viable Java HelloWorld contract project?
- Or should we start small and focus just on a single `.java` contract?

**Comment by djnicholson** [comment]
> Should I provide you a .zip with a minimum viable Java HelloWorld contract project?

This, please :)

I'm essentially looking for the minimal set of files that a Java developer would have in their VS Code workspace in order to author and compile a smart contract, then I can look into templatizing it.

**Comment by gsmachado** [comment]
@djnicholson finally.

Check this out: https://github.com/neow3j/neow3j-boilerplate

**Comment by djnicholson** [comment]
Thanks for pointing me at the sample project @gsmachado. A few follow-up questions... (Also please note that it has been 14+ years since I last developed in Java, so please forgive my ignorance in the space!)

It seems like [VS Code documentation](https://code.visualstudio.com/docs/languages/java) suggests using Maven for Java build, but the sample project uses Gradle.  I think we should have the extension generate a template project that is familiar to people who do day-to-day Java coding in VS Code (it seems like that may mean using Maven?)

Also it would be good to leave people in a state where they can instantly build and inspect errors using the tooling built-in to VS Code.  That means creating an appropriate `.vscode/tasks.json` file with an appropriate `problemMatcher`.  The sample project has `.vscode` in the `.gitignore` file so there may already be a sample `tasks.json` file that achieves this that I have not seen.

Assuming we do use Gradle:  Is it common to commit Gradle specific scripts and binaries (e.g. `gradle-wrapper.jar`, `gradlew`, `gradlew.bat`) to the project repo?

**Comment by gsmachado** [comment]
> Thanks for pointing me at the sample project @gsmachado. A few follow-up questions... (Also please note that it has been 14+ years since I last developed in Java, so please forgive my ignorance in the space!)
> 

No worries, man! 😄 

> It seems like [VS Code documentation](https://code.visualstudio.com/docs/languages/java) suggests using Maven for Java build, but the sample project uses Gradle. I think we should have the extension generate a template project that is familiar to people who do day-to-day Java coding in VS Code (it seems like that may mean using Maven?)
> 

This was a big topic when we started to develop the compiler and devpack for [neow3j](https://github.com/neow3j/neow3j) project. We discussed among us, with Neo, checked what users would like to have, and in the end, we decided to mainly support Gradle for now.

Some reasons:
* Gradle has a growing community (with the rise of projects like Kotlin, Scala, and AdoptJDK); versus Maven, which although has some active (and large) projects/members, it's losing traction over time.
* Gradle is the first option when developing mobile applications; since neow3j can be used to develop native Java/Kotlin mobile applications for Android, such fact added up in the equation.
* Gradle nicely supports Kotlin. We intend to support Kotlin language for smart contracts somewhen in Q2.
* In our vision roadmap, we would like to support audited and signed smart contract dependencies (published like a simple Gradle/Maven dependency, anywhere). Gradle could support that a bit better than Maven.

> Also it would be good to leave people in a state where they can instantly build and inspect errors using the tooling built-in to VS Code. That means creating an appropriate `.vscode/tasks.json` file with an appropriate `problemMatcher`. The sample project has `.vscode` in the `.gitignore` file so there may already be a sample `tasks.json` file that achieves this that I have not seen.
> 

Yes, we have a simple `.vscode/tasks.json` which I could include. I will let you know once I committed to the [neow3j-boilerplate](https://github.com/neow3j/neow3j-boilerplate) repo.

> Assuming we do use Gradle: Is it common to commit Gradle specific scripts and binaries (e.g. `gradle-wrapper.jar`, `gradlew`, `gradlew.bat`) to the project repo?

Yes, it is. It's a normal practice. Otherwise, people would need to install `gradle` in their computers. It's a convenient thing. People could live without it, sure. BTW: `gradlew` and `gradlew.bat` are shell scripts and not binaries.

The nice thing about the Gradle wrapper, is: if you're using MacOS/Linux, the command to execute is `./gradlew neow3jCompile`. If you're using Windows, the command is `gradlew.bat neow3jCompile`. And all dependencies will be solved for you.

What `gradlew` or `gradlew.bat` actually do is to use Java to execute the `gradle-wrapper.jar` to fetch all required gradle files specific to your platform. The `gradle-wrapper.properties` is simple metadata (also needs to be committed) from where the wrapper (`gradlew` or `gradlew.bat`) reads which Gradle version should be downloaded, which URL should be used, env var, etc etc.

In summary: gradle wrapper decreases complexity and it's one less dependency to the user, which seems a good thing. Maven doesn't have such a mechanism. People should always install both Java and Maven on their computers.

When using Gradle, the only thing that the user needs to have installed is [Java 1.8](https://adoptopenjdk.net). That's more or less similar to dotnet.

Now, let me give you some VS Code considerations:

1. If we would like to add support for Java smart contracts in the Neo3 Visual Devpack, it would be nice to require the VSCode plugin [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) `vscjava.vscode-java-pack` to be installed. This could be checked, for example, at the moment the user decides to create a Java-based smart contract.
2. The [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) (`vscjava.vscode-java-pack`) includes the extension [Language Support for Java](https://marketplace.visualstudio.com/items?itemName=redhat.java) `redhat.java`, which supports Gradle tasks and "auto build" out of the box.
3. Moreover, I think it would also make sense to check whether [Java 1.8](https://adoptopenjdk.net) is installed or not. I think you perform the same check for dotnet, right?

With all of that said, I think things should be very simple in the beginning. Maybe supporting the creation of a project is the first step, as you're already looking into it. Then, I might give you some code support to make some of the points (1), (2), (3) happen. I just need to align priorities first. 👍

**Comment by djnicholson** [comment]
Thanks for the clarifications @gsmachado 

The latest rolling build has some initial Java support.  https://github.com/ngdenterprise/neo3-visual-tracker/releases/tag/v0.0-master

Right now it can just create the file structure (doing string substitution based on user input).  It doesn't trigger a build yet (please share your same tasks.json file to point me in the right direction!) and it doesn't yet do any of the more fancy stuff like checking for java and related extension packs being installed. 

This is still a work in progress.

**Comment by gsmachado** [comment]
@djnicholson AWESOME work. We just tested it here. 💪 

We, Claude and I, got pretty excited to see this, directly integrated with the work you guys have been doing.

I think it's reasonable to close this issue for now. And I will create a more specific issue to discuss potential enhancements for the Java integration part of the boilerplate. Then we discuss how we can proceed, what you could enhance, what we (from AxLabs) have to provide you for a smoother experience, and so on and so forth.

Cool stuff!
