### ISSUE TITLE
*.nef files not found in the current workspace

### ISSUE THREAD

**Issue by gsmachado** [ngdenterprise/neo3-visual-tracker#34]
Hello @devhawk @djnicholson 

I have a Golang workspace, where I create a `token.go` file, which is a smart contract. I compiled this smart contract in the workspace, and a `token.nef` file was the output:

![image](https://user-images.githubusercontent.com/2124276/104050472-fafacb00-51e6-11eb-89b1-dbb5ce48fa95.png)

Then, after initializing the neo-express and stuff, I tried to deploy the contract like this:

![image](https://user-images.githubusercontent.com/2124276/104050555-15cd3f80-51e7-11eb-9b2b-b4c355f06b78.png)

Then, this message immediately appeared:

![image](https://user-images.githubusercontent.com/2124276/104050644-36959500-51e7-11eb-9010-ecfc8c88028c.png)

I believe this is a bug since I clearly have at least one `.nef` file in my vscode workspace.

**Comment by gsmachado** [comment]
ah... I don't know if that's a completely new feature or not, but it would be AWESOME to add the "Deploy contract" menu to the menu context of `*.nef` files.

Like, adding "Deploy contract" here:

![image](https://user-images.githubusercontent.com/2124276/104051509-89238100-51e8-11eb-89a2-97906f60a25c.png)

**Comment by djnicholson** [comment]
I think the problem is that there is no metadata file (and the text of the error message is a bit misleading!)

Adding a right click option for .nef will be possible (I'll still have to make it emit an error if the metadata cannot be found, though)

**Comment by gsmachado** [comment]
> I think the problem is that there is no metadata file (and the text of the error message is a bit misleading!)

hmmm... got it. So, what's the file extension the vscode extension is looking for?

And, most importantly: how does the vscode extensions associate that a metadata file belongs to a particular .nef file? (given the fact that a workspace could contain multiple compiled smart contracts (.nef's))

> Adding a right click option for .nef will be possible (I'll still have to make it emit an error if the metadata cannot be found, though)

Looking forward to it! 💯  👍

**Comment by devhawk** [comment]
NEON produces four files - .nef, .manifest.json, .abi.json and .nefdbgnfo. They are all generated in the same folder as the source DLL or project file resides. The NEF and manifest files are required for deployment. nefdbgnfo is used by the debugger. abi.json is redundant in NEO 3 - that information is duplicated in the manifest file.

**Comment by gsmachado** [comment]
@devhawk alright, neow3j outputs these files.

But it seems that some of the SDKs/compilers in the community does not follow this.

Do you think that we could write a small "standard" (NEP) for this? Or even, include this information to [NEP-14](https://github.com/neo-project/proposals/pull/119) and [NEP-15](https://github.com/neo-project/proposals/pull/114). I could try to propose this, since it gets clear to interoperability of tools at a higher level (e.g., vs code extensions, etc).

**Comment by devhawk** [comment]
There's already a neo proposal for the contract manifest: https://github.com/neo-project/proposals/pull/114

**Comment by gsmachado** [comment]
> NEON produces four files - .nef, .manifest.json, .abi.json and .nefdbgnfo. They are all generated in the same folder as the source DLL or project file resides and all have the same base file name. i.e. mycontract.dll generates mycontract.nef, mycontract.manifest.json, mycontract.nefdbgnfo and mycontract.abi.json.

@devhawk I don't see anywhere written that files should be named "*.manifest.json" or "*.nefdbgnfo.json", or "*.abi.json" in this proposal, though.

Again, just because NEON produces those files and that `neo3-visual-tracker` searches for those specific file name patterns doesn't mean that at the moment all compilers do the same. That's what I was referring to.

However, if `neo3-visual-tracker` get smart enough to detect those manifests based on file content, well, then it's a different story. Then compilers/developers could output any filename they want (by default). But, this is not an optimum solution IMHO (very time consuming, not scalable, etc etc).

**Comment by devhawk** [comment]
> @devhawk I don't see anywhere written that files should be named ".manifest.json" or ".nefdbgnfo.json", or "*.abi.json" in this proposal, though.

Good point @gsmachado regarding .manifest.json file extension. File extension for debug info however is [specified in NDX-DN11](https://github.com/ngdenterprise/design-notes/blob/master/NDX-DN11%20-%20NEO%20Debug%20Info%20Specification.md). And the .abi.json file is not used at all in neo 3, so we can safely ignore that file.

Technically, from the platform perspective, only the file contents of the contract binary and manifest matter - the platform doesn't store them in the file system with an extension anyway. However, for the sake of tooling, it seems we should include some text in both the NEF and manfest NEPs that specify file extension naming conventions when this content is stored in a file system. 

You want to open the issues or should I @gsmachado ?

**Comment by gsmachado** [comment]
@devhawk I [initiated the discussion](https://github.com/neo-project/proposals/pull/114#issuecomment-760180368) and Erik included in the [NEP](https://github.com/neo-project/proposals/commit/e74039ea73808c9aad444f2c79474ca386623fb7). 👍  😄

**Comment by gsmachado** [comment]
aaaaaand, it was also included [in this NEP](998a75eec0943fa5c7ae2c3de3db8f9d3789f81f). 🚀

**Comment by gsmachado** [comment]
@djnicholson you can assign this issue to me. I will test your last commits and I will come here to close the issue if that's the case, thanks.

**Comment by gsmachado** [comment]
I forgot to close this issue. My fault.

I tested and it's fine. Closing. 💪
