### ISSUE TITLE
transaction results (application logs)

### ISSUE THREAD

**Issue by gsmachado** [ngdenterprise/neo3-visual-tracker#35]
Do you guys support "application logs"? I mean, ok, I can invoke contracts and send the transactions... but, how do people see the transaction execution results (stack) in the Neo3 Visual Tracker?

Maybe this feature is not there yet but it's in the roadmap... in this case, let me know. 😄

**Comment by djnicholson** [comment]
We can use this issue to track adding that feature.

The main thing i need is the ability to query the application logs through the RPC server. Preferably it would be exposed as a method in the neonjs library (but if not, I can manually construct RPC requests).

**Comment by djnicholson** [comment]
I will shortly push a change that adds this to the transaction view:

![image](https://user-images.githubusercontent.com/2515705/105434383-50d06980-5c10-11eb-8e30-d74bcb22004f.png)

**Comment by djnicholson** [comment]
Builds as of d7053b4afbbe841f1a1893e55a13996cc00e6647 have this.  I'm open to feedback about the UI presentation.

Rolling build: https://github.com/ngdenterprise/neo3-visual-tracker/releases/tag/v0.0-master

@gsmachado let me know your thoughts, or close the issue if appropriate.

**Comment by gsmachado** [comment]
This is fine for now! Tested and it works as you implemented. Closing. 💪
