### ISSUE TITLE
List of Deployed Contracts

### ISSUE THREAD

**Issue by gsmachado** [ngdenterprise/neo3-visual-tracker#37]
As a user, while developing smart contracts, I would like to see a list of contracts deployed in my neo-express node and their respective addresses.

Right now, this is implicitly given in the "Invoke" panel/view, where the contract names + methods are listed:

![image](https://user-images.githubusercontent.com/2124276/105355486-85352d00-5bf2-11eb-88b2-7212d51b84e4.png)

However, I would like to have a summarized view of the deployed contracts, somewhere, where I could get basic info like contract address (with copy, ctrl+c, capability), some manifest attributes (like supported standards), etc. Like a simple list of contracts deployed on neo-express.

I'm not sure if I should also open an issue for neo-express or not...

**Comment by gsmachado** [comment]
Ok, maybe let me be more specific here:

Can you simply add a button, somewhere, that developers could copy the smart contract address of a deployed smart contract?

The use case is: the developer deploys a contract, doesn't copy/keep the contract address, and then opens the invoke screen to check where is the deployed contract.... but then realizes that the address is not displayed there. Then, I think it would be nice to place a button to copy the smart contract address somehow.

**Comment by ediopia** [comment]
@gsmachado I agreee with you. That will be very useful to have.
