### ISSUE TITLE
vscode command with optional params: neo3-visual-devtracker.express.transfer

### ISSUE THREAD

**Issue by gsmachado** [ngdenterprise/neo3-visual-tracker#40]
Since I'm creating code tours, and I intend to onboard new developers as easy as possible, it would be good to have some vscode commands with the possibility to be triggered without any user interaction. 

For example, let's suppose that I would like to create a code tour where I say: "please, perform X, Y, and Z in the Neo Visual DevTracker, OR click here to transfer 100 NEOs to address W."

The "click here" I would substitute to a vscode command, where I would, in this example, trigger the `neo3-visual-devtracker.express.transfer` command. At the moment, this can be done already... but the `vscode.window.openDialog` is always triggered no matter what (user interaction is always required).

Thus, it would be good to attach non-required parameters to the `neo3-visual-devtracker.express.transfer` command. Then, for example, if the `asset` param is not specified, but the `wallet` is specified, then the Neo Visual DevTracker extension would trigger the `.openDialog` only for the missing param.

You can check the [documentation for Command URIs](https://code.visualstudio.com/api/extension-guides/command#command-uris) to get a better grasp of what I'm talking about. 😄 

I'm creating this issue specifically for the `neo3-visual-devtracker.express.transfer` command, but this could be applied to other key commands like:

- `neo3-visual-devtracker.neo.newContract`: maybe, specify the template to be used? (e.g., java, dotnet, golang, etc etc)
- `neo3-visual-devtracker.express.contractDeploy`: specify the path for the `.nef` file (relative to the workspace, obviously), the `.manifest.json` file
- `neo3-visual-devtracker.neo.invokeContract`

But, I agree that we should maybe first to the `neo3-visual-devtracker.express.transfer` use case (because it's a bit more useful for us, at the moment) and then move on if necessary.

**Comment by djnicholson** [comment]
Notes to self:

- Need to ensure extension is activated (add onCommand events) whenever any command expected to be called programmatically from outside the extension
- "Click-jacking" risk: Need to require user interaction when there is a security need (e.g. probably fine to let someone single-click transfer assets on **express** instances, but not if the user is potentially interacting with MainNet). For now though, most interesting commands are scoped to neo3-visual-devtracker.express.* and only work on express instances. 
- Need to make sure that when paths are provided as external input that they truly are within the workspace (after being fully resolved to an absolute path)

**Comment by djnicholson** [comment]
Support for this on `neo3-visual-devtracker.express.transfer` coming soon.

**Comment by djnicholson** [comment]
For calling convention, I'm planning on doing something similar to the git command example in the [VS Code documentation](https://code.visualstudio.com/api/extension-guides/command#command-uris). So code to construct a URI to the transfer command would look something like this:

```
  const args = [{ asset: "NEO", amount: 1000, sender: "alice", receiver: "bob" }];
  const commandUri = vscode.Uri.parse(
    `command:neo3-visual-devtracker.express.transfer?${
      encodeURIComponent(JSON.stringify(args))
    }`
  );
```

**Comment by djnicholson** [comment]
Available for testing as of 46a5469b071b5b45eb046e7bcc75316f2d798272
[Rolling build](https://github.com/ngdenterprise/neo3-visual-tracker/releases/tag/v0.0-master)

**Comment by gsmachado** [comment]
Hey @djnicholson 

I've seen the committed code, and yes, that's what I was talking about. Cool. 💪 

Buuuuuuuuut, it doesn't work yet from the tests I performed... Let me try to give you the details of what I tried to do.

I created a simple and plain `WebView` panel with the `enableCommandUris` set to `true`. Then, I set some basic HTML content in the `WebView`, containing just a `<a>` tag (with the command URI that interests me). Check it out:

```javascript
	const panel = vscode.window.createWebviewPanel(
		"test",
		'TestStuff',
		vscode.ViewColumn.One,
		{
			// Enable javascript in the webview
			enableScripts: true,
			// Enable command-base URIs
			enableCommandUris: true
		}
	);
	panel.webview.html = `
	<html>
    	<body>
        	<a href="command:neo3-visual-devtracker.express.transfer?%5B%7B%22asset%22%3A%22NEO%22%2C%22amount%22%3A10%2C%22sender%22%3A%22Alice-account%22%2C%22receiver%22%3A%22Alice-account%22%7D%5D">Test</a>
    	</body>
	</html>
	`;
	panel.reveal();
```

The Command URI above was produced by the following code:

```javascript
const args = [{ asset: "NEO", amount: 10, sender: "Alice-account", receiver: "Alice-account" }];
const commandUri = vscode.Uri.parse(
	`command:neo3-visual-devtracker.express.transfer?${encodeURIComponent(JSON.stringify(args))}`
);
console.log(commandUri.toString());
```

When I try to click, the following happens:

![2021-02-03 at 1 09 01 - neo3-visual-tracker](https://user-images.githubusercontent.com/2124276/106679462-03afa880-65bd-11eb-928a-d6d588fdaf6d.gif)

My question is: did I miss something or anything else that should be changed in the implementation? 😄

**Comment by djnicholson** [comment]
Will take a look...

**Comment by djnicholson** [comment]
I had misunderstood how the URI encoded array was passed to the command handler.  Should be fixed in the latest rolling build.

**Comment by gsmachado** [comment]
@djnicholson thanks for it!

Now I can finally invoke the transfer from URI. Great!

However, one more thing:

[Lines 37 and 41](https://github.com/ngdenterprise/neo3-visual-tracker/blob/master/src/extension/commandArguments.ts#L37-L41) have the pattern `/[^a-z0-9]/gi`. Then, this implies that wallet names (or Neo addresses) can only start with lowercase? I think this needs to be changed... 😅

**Comment by djnicholson** [comment]
The `i` modifier should make the entire regex case-insensitive.  I just tried this in a JS debugger:

```
'David'.replace(/[^a-z0-9]/gi, "")
'David'
```

If you're not being allowed to specify uppercase wallet names, then the issue may be elsewhere...

**Comment by gsmachado** [comment]
> The `i` modifier should make the entire regex case-insensitive. I just tried this in a JS debugger:

You're absolutely right. Sorry, I overlooked it.

So.. great stuff, I will close this issue! Thanks for it. 😄
