### ISSUE TITLE
Dynamic neow3j lib version for Java smart contract boilerplate/template

### ISSUE THREAD

**Issue by gsmachado** [ngdenterprise/neo3-visual-tracker#48]
@djnicholson following up the very nice feature provided in the "Create smart contract" (Java) within the Neo3 Visual Tracker, it would be essential to provide the following for a great user experience:

1. After the user is asked about "java" or "dotnet", and "java" is selected, fetch the latest library version from Maven Central. This should be used in the smart contract boilerplate (to change the values in the `build.gradle` -- see my comment below).
2. If the user would like, it should also be possible to specify a custom version. For example, being able to specify a custom version is particularly useful if Maven Central can't be reached or the user is offline. If Maven Central **can** be reached, no worries, the latest version is the "default" one and the user will just press "ENTER" to move on. I think VSCode provides nice dialogs and ways to do this kind of thing, pretty easily.

If you're wondering how to fetch the latest version of io.neow3j, I wrote an article about this while researching to propose this issue: https://axlabs.medium.com/fetch-maven-central-info-from-the-command-line-7e63be3e9289 . I hope this is fine for you. 😄 

One last thing:

* The [plugin version](https://github.com/neow3j/neow3j-boilerplate/blob/main/build.gradle#L3) **and** the [dependencies' version](https://github.com/neow3j/neow3j-boilerplate/blob/main/build.gradle#L18-L20) should be dynamically set -- with the same version value.

Let me know if you have any questions. 👍

**Comment by gsmachado** [comment]
BTW: this can be applied not only to the Java smart contract boilerplate/template, but also for future potential integrations with other SDKs in the Neo ecosystem, where versions matter. For example, in neo-go.

In my opinion, it's not so difficult to implement and it paves the way for a nice integration in neo3-visual-tracker with other libs. 😄

**Comment by djnicholson** [comment]
PR: https://github.com/ngdenterprise/neo3-visual-tracker/pull/61

**Comment by gsmachado** [comment]
@djnicholson awesome! Really cool! 👍 💯 💪
