### ISSUE TITLE
Withdraw NEO/GAS from genesis account with 'neo3-visual-devtracker.express.transfer'

### ISSUE THREAD

**Issue by csmuller** [ngdenterprise/neo3-visual-tracker#50]
I just tried the newest Neo Blockchain Toolkit (version 2.0.5) and wasn't able to transfer tokens from the genesis account by using the "Neo Express 3: Transfer assets" command. This was possible previously. The *genesis* account would show up as an option next to the other accounts defined in the .neo-express file. It's not being displayed anymore.

Using `neoxp transfer 10 NEO genesis Alice` still worked, though.

**Comment by gsmachado** [comment]
Actually, the reason for this was: missing (or a mismatch) of the `magic` attribute in `default.neo-express` file.
