### ISSUE TITLE
(minor) Change version for java smart contract [neow3j]

### ISSUE THREAD

**Issue by gsmachado** [ngdenterprise/neo3-visual-tracker#54]
neow3j released version 3.8.0 for RC1.

It would be essential to change the version of neow3j in the neo3-visual-tracker [here](https://github.com/ngdenterprise/neo3-visual-tracker/blob/master/resources/new-contract/java/build.gradle.template.txt#L3) and [here](https://github.com/ngdenterprise/neo3-visual-tracker/blob/master/resources/new-contract/java/build.gradle.template.txt#L18-L20).

Anything else to be changed, @csmuller ?

**Comment by csmuller** [comment]
> Anything else to be changed, @csmuller ? 

No, that's all.
