### ISSUE TITLE
.NET SDK extension is not meant for external use

### ISSUE THREAD

**Issue by sfoslund** [ngdenterprise/neo3-visual-tracker#84]
We have been picking up telemetry from this extension indicating that it is leveraging the [vscode-dotnet-sdk extension](https://github.com/dotnet/vscode-dotnet-runtime). As noted in our [README](https://github.com/dotnet/vscode-dotnet-runtime/tree/main/vscode-dotnet-sdk-extension#net-education-bundle-sdk-install-tool), this tool is not intended for external use and was made specifically to be leveraged by the .NET education bundle. Please remove your dependency on the SDK extension as soon as possible, as it can potentially break your users when used outside of the context of the education bundle.

**Comment by sfoslund** [comment]
@djnicholson @devhawk

**Comment by sfoslund** [comment]
Thank you for the quick action! I noticed that you removed your reference to ms-dotnettools.vscode-dotnet-runtime as well. The runtime extension is fine for external use but the SDK extension is only internal, sorry for any confusion.

**Comment by devhawk** [comment]
No problem @sfoslund. We need the full SDK, so there's little point to us using one without the other.

**Comment by devhawk** [comment]
If your team ever does ship a version of the vscode-dotnet-sdk extension that's externally usable, we'd appreciate a heads up :)
