### ISSUE TITLE
new template C# project should create .sln file in root

### ISSUE THREAD

**Issue by devhawk** [ngdenterprise/neo3-visual-tracker#99]
If we are going to create the sample project in a sub directory, we should create a SLN file in the root that includes the csproj file of the contract.

I'm thinking the contract should go in the `src` folder and then we also have a `test` folder

**Comment by djnicholson** [comment]
The recent changes to the template create a dirs.proj in the root which I believe should be sufficient.  Assign back to me if you disagree.
